// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEnkGh_62W2gCfoFSx181CJS_Q8MkOTGY',
    appId: '1:567656719203:web:ec6a30b27ac1aa762ea956',
    messagingSenderId: '567656719203',
    projectId: 'gaduan-ba14c',
    authDomain: 'gaduan-ba14c.firebaseapp.com',
    storageBucket: 'gaduan-ba14c.appspot.com',
    measurementId: 'G-KQ08ZTJXE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwdHTwai6M8c1tJeBgfamwm77_sXiRH4w',
    appId: '1:567656719203:android:374f39f7369307092ea956',
    messagingSenderId: '567656719203',
    projectId: 'gaduan-ba14c',
    storageBucket: 'gaduan-ba14c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJOjozQFi01iQGS_XjjVAkm3yZBDVitYc',
    appId: '1:567656719203:ios:fb7a8718672229aa2ea956',
    messagingSenderId: '567656719203',
    projectId: 'gaduan-ba14c',
    storageBucket: 'gaduan-ba14c.appspot.com',
    iosClientId: '567656719203-nr12ntlme4tpqfjvvbn9vqtj91vququ8.apps.googleusercontent.com',
    iosBundleId: 'id.desa.timbangpurbalingga.gaduan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJOjozQFi01iQGS_XjjVAkm3yZBDVitYc',
    appId: '1:567656719203:ios:fb7a8718672229aa2ea956',
    messagingSenderId: '567656719203',
    projectId: 'gaduan-ba14c',
    storageBucket: 'gaduan-ba14c.appspot.com',
    iosClientId: '567656719203-nr12ntlme4tpqfjvvbn9vqtj91vququ8.apps.googleusercontent.com',
    iosBundleId: 'id.desa.timbangpurbalingga.gaduan',
  );
}
